name: Deploy Build Files Production

on:
    push:
        branches:
            - master
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - ".prettierrc"
            - ".env.*"

    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

env:
    NODE_ENV: production

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Pull the latest code
              uses: actions/checkout@master

            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install dependencies
              run: npm install --include dev

            - name: Build files
              run: npm run build

            - name: replicate directory structure
              run: |
                  mkdir -p remote/dist
                  cp -rT ./dist/ remote/dist/
                  cp -rT ./package.json remote/package.json

            - name: Push to build branch
              uses: s0/git-publish-subdir-action@v2.5.1
              env:
                  REPO: self
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
                  BRANCH: build/master # The branch name where you want to push the assets
                  FOLDER: remote # The directory where your assets are generated
                  MESSAGE: "Build: ({sha}) {msg}" # The commit message
